kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: "fast-storage"
    fsType: "ext4"
