kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: "fast-storage"
    fsType: "ext4"
